name: ezeewash_rider
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  slide_to_act: ^2.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #google maps:
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.1.0

  # Backend & State
  supabase_flutter: ^2.12.2
  shared_preferences: ^2.5.5

  # UI & Fonts
  google_fonts: ^8.0.2

  # Location & Navigation
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^21.0.0

  # Push Notifications
  firebase_core: ^4.6.0
  onesignal_flutter: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/rider_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/rider_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/rider_logo.png"
  fullscreen: true
  android_12:
    color: "#ffffff"
    icon_background_color: "#ffffff"
    image: "assets/icon/rider_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/rider_logo.png