name: ezeewash_rider
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Backend & State
  supabase_flutter: ^2.12.2
  shared_preferences: ^2.5.5

  # UI & Fonts
  google_fonts: ^8.0.2

  # Location & Navigation (Using Stable Versions)
  geolocator: ^13.0.2
  url_launcher: ^6.3.2
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.2

  # Push Notifications
  firebase_core: ^4.6.0
  onesignal_flutter: ^5.4.6
  # 🟢 FIXED: Removed firebase_messaging to stop the conflict with OneSignal!
  # 🟢 FIXED: Removed slide_to_act since you are using the Tap button now.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "assets/icon/rider_logo.png"