// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgOLmqcRc1oRhs8rWI8DpaoaFnEpRPBE',
    appId: '1:305466619382:web:974c017ac134d474f003d7',
    messagingSenderId: '305466619382',
    projectId: 'ezeewash-ed742',
    authDomain: 'ezeewash-ed742.firebaseapp.com',
    storageBucket: 'ezeewash-ed742.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHe9Q-1Qq8qZVTxx6barusshUaoNOf4s',
    appId: '1:305466619382:android:afa47bfa793959c2f003d7',
    messagingSenderId: '305466619382',
    projectId: 'ezeewash-ed742',
    storageBucket: 'ezeewash-ed742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDMBEvYWpHg_lcGf3zipavWuCoblhqKg',
    appId: '1:305466619382:ios:09993a2f28e9671cf003d7',
    messagingSenderId: '305466619382',
    projectId: 'ezeewash-ed742',
    storageBucket: 'ezeewash-ed742.firebasestorage.app',
    iosBundleId: 'com.example.ezeewashRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDMBEvYWpHg_lcGf3zipavWuCoblhqKg',
    appId: '1:305466619382:ios:09993a2f28e9671cf003d7',
    messagingSenderId: '305466619382',
    projectId: 'ezeewash-ed742',
    storageBucket: 'ezeewash-ed742.firebasestorage.app',
    iosBundleId: 'com.example.ezeewashRider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUgOLmqcRc1oRhs8rWI8DpaoaFnEpRPBE',
    appId: '1:305466619382:web:2bf55f161ad303fff003d7',
    messagingSenderId: '305466619382',
    projectId: 'ezeewash-ed742',
    authDomain: 'ezeewash-ed742.firebaseapp.com',
    storageBucket: 'ezeewash-ed742.firebasestorage.app',
  );
}
